name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      _JAVA_OPTIONS: "-Xmx4g"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          workdir: /github/workspace
          repository_root: /github/workspace
          buildozer_version: '1.2.0'
        env:
          USER: runner

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: ./.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/**/build/outputs/apk/debug/*.apk
