name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      _JAVA_OPTIONS: "-Xmx4g"   # Give Java more memory

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          workdir: .
          buildozer-version: stable
